export const mobileSocketEvents = {
  sendMessage: "SEND_MESSAGE",
  joinChat: "JOIN_CHAT",
  typing: "TYPING",
  stopTyping: "STOP_TYPING",
  deleteMessage: "DELETE_MESSAGE",
  userOnline: "USER_ONLINE",
  userOffline: "USER_OFFLINE",
  presenceSync: "PRESENCE_SYNC",
  newMessage: "NEW_MESSAGE",
  messageDelivered: "MESSAGE_DELIVERED",
  messageSeen: "MESSAGE_SEEN",
  messageDeleted: "MESSAGE_DELETED",
  chatUpdated: "CHAT_UPDATED",
  friendRequestReceived: "FRIEND_REQUEST_RECEIVED",
  friendRequestAccepted: "FRIEND_REQUEST_ACCEPTED",
  friendRequestRejected: "FRIEND_REQUEST_REJECTED",
  reactionAdded: "REACTION_ADDED",
  reactionRemoved: "REACTION_REMOVED",
} as const;
